//
//  PDFExporter.swift
//  ExcelExplorer
//
//  Created by Jordan Koch on 2026-01-21.
//  Adapted from Bastion's PDFGenerator pattern
//

import Foundation
import CoreGraphics
import AppKit

class PDFExporter {
    // MARK: - Export Single Sheet
    static func exportSheet(_ sheet: SheetData, to url: URL) async throws {
        let pdfData = NSMutableData()
        guard let consumer = CGDataConsumer(data: pdfData as CFMutableData) else {
            throw ExportError.fileWriteError
        }

        var mediaBox = CGRect(x: 0, y: 0, width: 792, height: 612) // Letter size landscape
        guard let pdfContext = CGContext(consumer: consumer, mediaBox: &mediaBox, nil) else {
            throw ExportError.fileWriteError
        }

        // Begin PDF document
        pdfContext.beginPDFPage(nil)

        // Title
        drawText(pdfContext, text: "Spreadsheet: \(sheet.name)", at: CGPoint(x: 50, y: 560), size: 18, bold: true)

        // Draw table
        var yPos: CGFloat = 520
        let cellWidth: CGFloat = 100
        let cellHeight: CGFloat = 20
        let startX: CGFloat = 50

        // Headers
        for (index, header) in sheet.headers.prefix(7).enumerated() {
            let xPos = startX + CGFloat(index) * cellWidth
            drawText(pdfContext, text: header, at: CGPoint(x: xPos + 5, y: yPos - 15), size: 10, bold: true)

            // Draw cell border
            pdfContext.setStrokeColor(gray: 0.5, alpha: 1.0)
            pdfContext.setLineWidth(0.5)
            pdfContext.stroke(CGRect(x: xPos, y: yPos - cellHeight, width: cellWidth, height: cellHeight))
        }

        yPos -= cellHeight

        // Data rows (limited to fit on page)
        let maxRows = min(20, sheet.rowCount - 1)
        for row in 1...maxRows {
            for (index, cell) in sheet.cells[row].prefix(7).enumerated() {
                let xPos = startX + CGFloat(index) * cellWidth
                drawText(pdfContext, text: cell.displayValue, at: CGPoint(x: xPos + 5, y: yPos - 15), size: 9)

                // Draw cell border
                pdfContext.setStrokeColor(gray: 0.7, alpha: 1.0)
                pdfContext.setLineWidth(0.3)
                pdfContext.stroke(CGRect(x: xPos, y: yPos - cellHeight, width: cellWidth, height: cellHeight))
            }

            yPos -= cellHeight

            // Check if we need a new page
            if yPos < 50 {
                pdfContext.endPDFPage()
                pdfContext.beginPDFPage(nil)
                yPos = 560
            }
        }

        // Footer
        drawText(
            pdfContext,
            text: "Generated by Excel Explorer - \(Date().formatted(date: .abbreviated, time: .shortened))",
            at: CGPoint(x: 50, y: 30),
            size: 8
        )

        // End PDF
        pdfContext.endPDFPage()
        pdfContext.closePDF()

        // Write to file
        try pdfData.write(to: url)
    }

    // MARK: - Export Workbook (Multiple Sheets)
    static func exportWorkbook(_ workbook: WorkbookData, to url: URL) async throws {
        let pdfData = NSMutableData()
        guard let consumer = CGDataConsumer(data: pdfData as CFMutableData) else {
            throw ExportError.fileWriteError
        }

        var mediaBox = CGRect(x: 0, y: 0, width: 792, height: 612)
        guard let pdfContext = CGContext(consumer: consumer, mediaBox: &mediaBox, nil) else {
            throw ExportError.fileWriteError
        }

        // Summary page
        pdfContext.beginPDFPage(nil)
        drawText(pdfContext, text: "Workbook: \(workbook.filename)", at: CGPoint(x: 50, y: 560), size: 24, bold: true)
        drawText(pdfContext, text: "Sheets: \(workbook.sheets.count)", at: CGPoint(x: 50, y: 520), size: 14)

        var yPos: CGFloat = 480
        for (index, sheet) in workbook.sheets.enumerated() {
            drawText(
                pdfContext,
                text: "\(index + 1). \(sheet.name) (\(sheet.rowCount) rows × \(sheet.columnCount) columns)",
                at: CGPoint(x: 70, y: yPos),
                size: 12
            )
            yPos -= 25
        }

        pdfContext.endPDFPage()

        // Export each sheet on separate pages
        for sheet in workbook.sheets {
            pdfContext.beginPDFPage(nil)

            // Sheet title
            drawText(pdfContext, text: "Sheet: \(sheet.name)", at: CGPoint(x: 50, y: 560), size: 18, bold: true)

            // Draw table (similar to single sheet export)
            var yPos: CGFloat = 520
            let cellWidth: CGFloat = 100
            let cellHeight: CGFloat = 20
            let startX: CGFloat = 50

            // Headers
            for (index, header) in sheet.headers.prefix(7).enumerated() {
                let xPos = startX + CGFloat(index) * cellWidth
                drawText(pdfContext, text: header, at: CGPoint(x: xPos + 5, y: yPos - 15), size: 10, bold: true)
                pdfContext.setStrokeColor(gray: 0.5, alpha: 1.0)
                pdfContext.setLineWidth(0.5)
                pdfContext.stroke(CGRect(x: xPos, y: yPos - cellHeight, width: cellWidth, height: cellHeight))
            }

            yPos -= cellHeight

            // Data rows
            let maxRows = min(20, sheet.rowCount - 1)
            for row in 1...maxRows {
                for (index, cell) in sheet.cells[row].prefix(7).enumerated() {
                    let xPos = startX + CGFloat(index) * cellWidth
                    drawText(pdfContext, text: cell.displayValue, at: CGPoint(x: xPos + 5, y: yPos - 15), size: 9)
                    pdfContext.setStrokeColor(gray: 0.7, alpha: 1.0)
                    pdfContext.setLineWidth(0.3)
                    pdfContext.stroke(CGRect(x: xPos, y: yPos - cellHeight, width: cellWidth, height: cellHeight))
                }
                yPos -= cellHeight
            }

            pdfContext.endPDFPage()
        }

        pdfContext.closePDF()
        try pdfData.write(to: url)
    }

    // MARK: - Helper: Draw Text
    private static func drawText(_ context: CGContext, text: String, at point: CGPoint, size: CGFloat, bold: Bool = false) {
        let font = bold ? NSFont.boldSystemFont(ofSize: size) : NSFont.systemFont(ofSize: size)
        let attributes: [NSAttributedString.Key: Any] = [
            .font: font,
            .foregroundColor: NSColor.black
        ]

        let attributedString = NSAttributedString(string: text, attributes: attributes)

        context.saveGState()
        context.translateBy(x: 0, y: 612) // Flip coordinate system
        context.scaleBy(x: 1, y: -1)

        let textRect = CGRect(x: point.x, y: 612 - point.y - size, width: 700, height: size + 10)
        attributedString.draw(in: textRect)

        context.restoreGState()
    }
}
